# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: wabrez-711-${self:custom.stage}-${self:custom.region}-api3

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  subscriptionId: d36d0808-a967-4f73-9fdc-32ea232fc81d
  resourceGroup: wabrez-711-${self:custom.region}-rg
  apim:
    name: wabrez-711-${self:custom.stage}-${self:custom.region}-apim
    api: 
      name: wabrez-711-${self:custom.stage}-${self:custom.region}-api3
      subscriptionRequired: false
      displayName: api3
      description: Description of the API
      protocols: 
        - https
      path: api3
      tags:
        - tag1
        - tag2
      authorization: none
    cors: 
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"
  armTemplate:
    file: arm/template.json
    parameters:
      location: West US
      functionAppName: wabrez-711-${self:custom.stage}-${self:custom.region}-api3
      appServicePlanName: wabrez-711-${self:custom.stage}-${self:custom.region}-asp-win
      apiManagementName: wabrez-711-${self:custom.stage}-${self:custom.region}-apim
      hostingEnvironmentName: wabrez-711-${self:custom.region}-ase
      virtualNetworkName: wabrez-711-${self:custom.region}-vnet
      storageAccountName: wabrez711${self:custom.stage}${self:custom.region}stg
      appInsightsName: wabrez-711-${self:custom.stage}-${self:custom.region}-appinsights

plugins:
  - serverless-azure-functions
  - serverless-webpack

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'westus'}

  webpack:
    keepOutputDirectory: true

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  health:
    handler: src/handlers/health.handler
    apim:
      operations:
        - method: get
          urlTemplate: /health
          displayName: Health
    events:
      - http: true
        x-azure-settings:
          methods: 
            - GET
          authLevel : function
      - http: true
        x-azure-settings:
          direction: out
          name: res
  hello:
    handler: src/handlers/hello.handler
    apim:
      operations:
        - method: get
          urlTemplate: /hello
          displayName: Hello
    events:
      - http: true
        x-azure-settings:
          methods: 
            - GET
          authLevel : function
      - http: true
        x-azure-settings:
          direction: out
          name: res
  goodbye:
    handler: src/handlers/goodbye.handler
    apim:
      operations:
        - method: get
          urlTemplate: /goodbye
          displayName: Goodbye
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel : function
      - http: true
        x-azure-settings:
          direction: out
          name: res